/*==============================================================================================
 *         Copyright (c), NXP Semiconductors
 *
 *       All rights are reserved. Reproduction in whole or in part is
 *      prohibited without the written consent of the copyright owner.
 *  NXP reserves the right to make changes without notice at any time.
 * NXP makes no warranty, expressed, implied or statutory, including but
 * not limited to any implied warranty of merchantability or fitness for any
 *particular purpose, or that the use will not infringe any third party patent,
 * copyright or trademark. NXP must not be liable for any loss or damage
 *                          arising from its use.
 */

/*==============================================================================================
 *
 *   File name:  hw_config.c
 *
 *  Created on:
 *      Author:
 *
 *     Hystory:
 */

/*----------------------------------------------------------------------------------------------
 * Includes
 ---------------------------------------------------------------------------------------------*/
#include <stdio.h>
#include <ph_TypeDefs.h>
#include <ph_Status.h>

#include <ph_NxpBuild.h>
#include <phbalReg.h>
#include <phhalHw.h>

#include "phhwConfig.h"

#include <phOsal.h>
#include <phpalI18092mT.h>
#include <phlnLlcp.h>
#include <phhalHw_Rc523_Reg.h>


/*----------------------------------------------------------------------------------------------
 * Local macros and definitions
 ---------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Global variables
 * -------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Local variables
 * -------------------------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------------------------
 * Local function declaration
 ---------------------------------------------------------------------------------------------*/
#if defined (NXPBUILD__PHHAL_HW_RC523) && defined (NXPBUILD__PHHAL_HW_RC663)
#error ** Mismatch reader device - PN512 and RC663 are alloved together **
#endif


/*----------------------------------------------------------------------------------------------
 * Global function prototypes
 ---------------------------------------------------------------------------------------------*/


/* **************************************
 * Initialize interface link            *
 * **************************************/

/* =============================================================================================
 * Function:	Set_Interface_Link
 *
 * brief:
 *   Initialize interface link
 *   GPIOSetDir sets the direction in GPIO port.
 *   1 out, 0 input
 *
 *   GPIOSetValue sets/clears a bitvalue in a specific bit position
 *   in GPIO portX(X is the port number.)
 *   Our RC523 will act in slave mode. START and STOP conditions are
 *   generated by the master.
 *
 * -------------------------------------------------------------------------------------------*/
void Set_Interface_Link(void)
{

}

/* **************************************
 * handle Reset of the reader chip      *
 * **************************************/

/*==============================================================================================
 * Function:   Reset_reader_device
 *
 * brief:   reset the reader chip
 *
 * -------------------------------------------------------------------------------------------*/
void Reset_reader_device(void)
{
	
#if defined NXPBUILD__PHHAL_HW_RC663
	int i;
	/* delay of ~1,2 ms */
	for (i = 0x2800; i > 0; i --);
	
#endif

}
/* **************************************
 * handle GPIO                          *
 * **************************************/

/*==============================================================================================
 * Function:	GPIO_Init
 *
 * brief:
 *
 * -------------------------------------------------------------------------------------------*/
void GPIO_Init(void)
{

}

/*==============================================================================================
 * Function:	Set_Port
 *
 * brief:
 *
 * -------------------------------------------------------------------------------------------*/
void Set_Port(void)
{

}

/*==============================================================================================
 * Function:	LedOn
 *
 * brief:	switch the LED on
 *
 * -------------------------------------------------------------------------------------------*/
void LedOn(void)
{

}

/*==============================================================================================
 * Function:	LedOff
 *
 * brief:	switch the LED off
 *
 * -------------------------------------------------------------------------------------------*/
void LedOff(void)
{

}

#ifdef NXPBUILD__PHHAL_HW_RC523
/*==============================================================================================
 * Data structure dedicated to keep important data from application.
 *
 * params:		pHal	[in]	Pointer to RdLib HAL data parameter component. Its used to handle
 * 								registers of reader IC when configured the interrupts by the Set_Interrupt()
 * 								function.
 * 				pOsal	[in]	Pointer to OSAL parameter component. Necessary to call a correct
 * 								application callback from within timer interrupt handler.
 * 				pData	[in]	Pointer to data from the application. The data are expected to be
 * 								handled within IRQ handlers of this project.
 * -------------------------------------------------------------------------------------------*/
static struct{
	void			*pHal;
	void			*pOsal;
	volatile void	*pData_ready;
}appData;
/*==============================================================================================
 * Function:	appDataInit
 *
 * brief:		This function configures pin IRQ on MCU side and IRQ generation on reader IC.
 * 				In result dedicated interrupt requests from reader IC are escalated to the host MCU.
 *				The function is used by NFC Target.
 *
 * params:		pHal	[in]	Pointer to RdLib HAL data parameter component. Its used to handle
 * 								registers of reader IC when configured the interrupts by the Set_Interrupt()
 * 								function.
 * 				pOsal	[in]	Pointer to OSAL parameter component. Necessary to call a correct
 * 								application callback from within timer interrupt handler.
 * 				pData	[in]	Pointer to data from the application. The data are expected to be
 * 								handled within IRQ handlers of this project. *
 * -------------------------------------------------------------------------------------------*/
void appDataInit( void	*pHal,
				  void	*pOsal,
				  void	*pData)
{
	appData.pHal 			  = pHal;
	appData.pOsal 			  = pOsal;
	appData.pData_ready 	  = pData;

	return;
}
#endif /* NXPBUILD__PHHAL_HW_RC523 */



int32_t RS232_Write()
{
  printf("RS232_Write\n");
  return 0;
}

int32_t RS232_Read()
{
  printf("RS232_Read\n");
  return 0;
}

int32_t RS232_ReadWrite()
{
  printf("RS232_ReadWrite\n");
  return 0;
}

/*----------------------------------------------------------------------------------------------
 * End of file
 ---------------------------------------------------------------------------------------------*/

